server.port=8080
server.servlet.session.cookie.name=B2BSESSIONID

spring.application.name=b2b-shop

spring.security.oauth2.client.registration.authenid.client-id=b2b-shop
spring.security.oauth2.client.registration.authenid.client-secret=b2b-shop-secret
spring.security.oauth2.client.registration.authenid.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.authenid.redirect-uri=http://localhost:8081/login/oauth2/code/authenid
spring.security.oauth2.client.registration.authenid.scope=openid,profile,email
spring.security.oauth2.client.registration.authenid.client-name=AuthenID
spring.security.oauth2.client.registration.authenid.client-authentication-method=client_secret_basic

spring.security.oauth2.client.provider.authenid.issuer-uri=http://localhost:9000
